name: Spring Boot 배포 자동화

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 권한 부여 및 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test # 테스트는 제외하고 빌드

      - name: 빌드 결과물과 설정 파일들을 EC2로 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "build/libs/*.jar,Dockerfile,docker-compose.yaml"
          target: "/home/ubuntu/andlife"
          strip_components: 0

      - name: EC2에서 Docker Compose 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          # env 항목을 추가하여 GitHub Secrets의 값을 전달합니다.
          envs: MYSQL_PASSWORD
          script: |
            cd /home/ubuntu/andlife
            docker compose down
            # 실행 시점에 환경 변수 주입
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} docker compose up --build -d